---
language: java

jdk:
- oraclejdk8

before_install:
  - ls -lthra
  - java -version
  - echo "starting build..."

install:
  - mvn install

script:
  - echo "some more stuff..."
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
